name: Run Benchmark Tests

on:
  workflow_dispatch:

jobs:
  benchmark:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
      LOG_RESPONSE: true
      SAVE_SCREENSHOT: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          npx -y playwright install --with-deps chromium

      - name: Run Benchmark Tests
        run: |
          yarn build
          yarn test

      - name: Add benchmark result to repository and push
        run: |
          FILENAME="tests_${GITHUB_RUN_NUMBER}.json"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./outputs/$FILENAME
          git commit -m "[skip ci] Add benchmark result build=${GITHUB_RUN_NUMBER}"
          git push origin HEAD:main

      - name: Upload Benchmark Outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-test-outputs
          path: ./outputs/*

      - name: Upload Benchmark Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-test-reports
          path: ./reports/*

      - name: Upload Benchmark Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-test-screenshots
          path: ./screenshots/*

      - name: Install jq for listing output *.json files
        run: sudo apt-get install jq -y

      - name: Create manifest.json file with all outputs *.json files
        run: |
          cp -r outputs/*.json reports/
          cd reports
          ls *.json | jq -R -s '{files: split("\n")[:-1]}' > manifest.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./reports
          keep_files: false
          force_orphan: true
